FROM ghcr.io/eooce/nodejs:main

ENV NAME=Pipeops \
    NEZHA_SERVER=nz.f4c.cn \
    NEZHA_KEY=zXlotYmDKT9Y2Jo3NF \
    CFIP=www.visa.com.tw \
    ARGO_DOMAIN=pipeops.ct8.pp.ua \
    ARGO_AUTH=eyJhIjoiZDQzMzYxM2ZmODQxNWMyMGM3NDY0YTFkN2M2OWE2MDEiLCJ0IjoiYmFmZjc0MmMtMWNmOC00NGUyLWIzYjktMjRmN2ViYTI0ZTRkIiwicyI6IlpETXlPRGxoTm1VdFpEQmtOQzAwTTJRMUxXSXpZekV0Tm1NNU5qazFPV1F5TVRVeiJ9
